version: '3.8'
services:
  db:
    image: 'postgres:13'
    restart: always
    environment:
      POSTGRES_DB: onyx        
      POSTGRES_USER: onyx          
      POSTGRES_PASSWORD: changeme  
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'