services:
  db:
    image: 'postgres:13'
    container_name: onyx-db
    restart: always
    environment:
      POSTGRES_DB: onyx        
      POSTGRES_USER: onyx          
      POSTGRES_PASSWORD: changeme  
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - onyx-network
  onyx:
    container_name: onyx
    image: onyxassistant/onyx
    env_file:
      - .env
    networks:
      - onyx-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
  onyx-proxy:
    image: traefik:v2.5
    container_name: onyx-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - onyx-network
    labels:
      - "traefik.enable=true"

networks:
  onyx-network:
    name: onyx-network
    external: true