services:
  db:
    image: 'postgres:13'
    container_name: onyx-db
    restart: always
    environment:
      POSTGRES_DB: onyx        
      POSTGRES_USER: onyx          
      POSTGRES_PASSWORD: changeme  
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - onyx-network
  frontend:
    container_name: onyx-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/core:/app/core
    env_file:
      - .env
    networks:
      - onyx-network
    ports:
      - '3000:3000'
  backend:
    container_name: onyx-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
    networks:
      - onyx-network
    ports:
      - '5000:5000'

networks:
  onyx-network:
    name: onyx-network
    external: true