version: "3"

tasks:
  build:
    desc: "Build the docker images"
    cmds:
      - cd gateway && docker build -t onyxassistant/onyx-gateway .
      - cd web && docker build -t onyxassistant/onyx-web .

  dev:
    desc: "Run the docker images"
    cmds:
      - docker compose -f docker-compose.dev.yml up

  prod:
    desc: "Run the docker images"
    cmds:
      - docker compose up
