version: "3"

tasks:
  build-docker:
    desc: "Build the docker images"
    cmds:
      - cd backend && docker build -t onyx-backend -f Dockerfile .
      - cd frontend && docker build -t onyx-frontend -f Dockerfile .

  build-docker-dev:
    desc: "Build the docker images"
    cmds:
      - docker compose -f docker-compose.dev.yml build

  dev:
    desc: "Run the docker images"
    cmds:
      - docker compose -f docker-compose.dev.yml up

  prod:
    desc: "Run the docker images"
    cmds:
      - docker compose up
