name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: onyxassistant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push onyx:dev
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: onyxassistant/onyx:dev
        target: development

    - name: Build and push onyx:latest
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: onyxassistant/onyx:latest
