name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: onyxassistant
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push onyx-gateway
      uses: docker/build-push-action@v5
      with:
        context: gateway
        push: true
        tags: onyxassistant/onyx-gateway
        target: development
        platforms: linux/amd64,linux/arm64

    - name: Build and push onyx-web
      uses: docker/build-push-action@v5
      with:
        context: web
        push: true
        tags: onyxassistant/onyx-web
        platforms: linux/amd64,linux/arm64
